project:
  type: website
  output-dir: docs

website:
  title: "Ruby Krasnow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research
      - href: resources.qmd
        text: Resources
    right:
      - icon: github
        href: https://github.com/rmk118
      - icon: envelope-fill
        href: mailto:rubykrasnow@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/ruby-krasnow/

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false



