project:
  type: website
  output-dir: docs

website:
  title: "Ruby Krasnow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pubs.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
    right:
      - icon: envelope-fill
        href: mailto:rubykrasnow@gmail.com
      - icon: github
        href: https://github.com/rmk118
      - icon: linkedin
        href: https://www.linkedin.com/in/ruby-krasnow/
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0009-0007-0531-8420 
      - text: "{{< fa brands x-twitter >}}"
        href: https://twitter.com/rmk_118

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false



