---
title: "Research"
---

# Crustacean size at maturity

    
    

# Aquaculture

 -   Sugar kelp (*Saccharina latissima*) Dynamic Energy Budget models
 -   Interactive effects of cultivation method & environmental conditions on the growth, shape, mortality, and biofouling of American oysters (*Crassostrea virginica*)



# Misc.

I have made a substantial start on these projects through research I have done for my academic classes, but do not have a current plan for turning my preliminary work into a publishable product. If you are interested in collaborating on any of these topics, please reach out.

-   Function and composition of the kelp microbiome
-   Modeling the spread of invasive tunicates with species distribution models (SDMs) and/or reaction-diffusion equations
    -   Taking a multi-model approach for invasion prediction (combining niche modeling, GAMs, ML techniques, partial differential equation and integrodifference equations, etc.) to improve predictive accuracy and better inform control efforts
