---
  title: "Publications"
---

Cleaver, C., Bayer, S., McMahan, M., Kiffney, T., Krasnow, R., Jekielek, P., Moritz, B., Batchelder, J., Arnold, S., Guenther, C., Miller, D., Miller, T., Wahle, R., Wotton, J., & Young, T. (2026). The effects of small-scale closed areas on the Atlantic sea scallop (*Placopecten magellanicus*) in Maine. *Marine and Coastal Fisheries, 18*(3), vtaf041. <https://doi.org/10.1093/mcfafs/vtaf041>

Krasnow, R., Kiffney, T., Cuddy, R., & Brady, D. (2025). Interacting effects of environment and cultivation method on biofouling of farmed oysters (*Crassostrea virginica*). *Journal of the World Aquaculture Society*, *56*(3), e70012. <https://doi.org/10.1111/jwas.70012>

Krasnow, R., Kaufman, L., & Deyle, E. (2025). Making the most of available data: A case study of converging analyses to model an emerging fishery for Jonah crab (*Cancer borealis*). *Fish & Fisheries*. <https://doi.org/10.1111/faf.70011>

Krasnow, R., Kiffney, T., Coleman, S., Cuddy, R., & Brady, D. (2025). Quantifying oyster aquaculture lease acceptance: A case study on repurposed Maine lobster pounds. *Aquaculture Reports, 44,* 103067. <https://doi.org/10.1016/j.aqrep.2025.103067>

Krasnow, R. (2025). Making partial differential equations accessible to ecologists. *Nature Reviews Biodiversity*, *1*, 87–87. <https://doi.org/10.1038/s44358-025-00017-0> ([full text link](https://rdcu.be/eacVm))

Chammout, H., Adkins, D. L., Al-Olimat, A. K., …, Krasnow, R., … & Kagey, J. D. (2024). G.3.2 is a novel allele of the gene connector enhancer of ksr (cnk) in Drosophila melanogaster. *microPublication Biology*. <https://doi.org/10.17912/micropub.biology.001290>

Krasnow, R., Gonzalez, S., & Lindell, S. (2024). Improving growth models of cultivated sugar kelp, Saccharina latissima, by accounting for intraspecific variation in thermal tolerance. *Journal of the World Aquaculture Society*, *55*(5), e13085. <https://doi.org/10.1111/jwas.13085>

## Preprints

Pick, J. L., Allen, B., Bachelot, B., Bairos-Novak, K. R., Brand, J. A., Class, B. A., Dallas, T., D’Amelio, P. B., Fenollosa, E., Fernández-Juricic, E., Gomes, D. G. E., Grainger, M., Guillemaud, T., John, C., Krasnow, R., Lagisz, M., Lequime, S., … Ivimey-Cook, E. R. (2025). *The SORTEE Guidelines for Data and Code Quality Control in Ecology and Evolutionary Biology*. EcoEvoRxiv. <https://doi.org/10.32942/X24P8S>

## Magazine Articles & Blog Posts

Peters, J., Lewis, A., Wilson, A., Kowalski, C., Brookson, C. B., Koren, G., Moustahfid, H., O’Grady, H., McLachlan, J., Zobitz, J., Lofton, M., Krasnow, R., & Sabet, S. S. (2025). Resources for Reviewing Code. *Ecological Forecasting Initiative*. [https://ecoforecast.org/resources-for-reviewing-code](https://ecoforecast.org/resources-for-reviewing-code/)

Gruson, H., Butland, S., & Krasnow, R. (2025). The Dynamic Relationship of Forks with Their Upstream Repository. *rOpenSci*. <https://doi.org/10.59350/5n1pv-3sg04>.

Krasnow, R. (2025). A Tasty Enigma. *The Marine Biologist*, 33, 12–16. <https://www.yumpu.com/en/document/read/69919198/the-marine-biologist-issue-33>

Krasnow, R. (2022). Reviving lobster pounds as oyster farms. *The Working Waterfront*. <https://www.islandinstitute.org/working-waterfront/reviving-lobster-pounds-as-oyster-farms/>

## Presentations

Krasnow, R. (2025). `morphmat`: An R Package to Estimate Crustacean Size at Maturity. Oral presentation. *UMaine* *School of Marine Sciences Graduate Symposium*, Walpole, ME.

Krasnow, R. & Shank, B. (2024). Modeling spatial variation in Jonah crab (*Cancer borealis*) size at maturity. Poster. *American Fisheries Society Annual Meeting*, Honolulu, HI

Krasnow, R. & Shank, B. (2024). Modeling spatial variation in Jonah crab (*Cancer borealis*) size at maturity. Poster. *Ecological Society of America Annual Meeting*, Long Beach, CA

Krasnow, R. & Shank, B. (2024). Modeling spatial variation in Jonah crab (*Cancer borealis*) size at maturity. Poster. *NOAA Science & Education Symposium*, Silver Spring, MD

Krasnow, R., Kiffney, T., Coleman, S., Cuddy, R., & Brady, D. (2024). Quantifying oyster aquaculture lease acceptance: a case study on repurposed Maine lobster pounds. Oral presentation. *Northeast Aquaculture Conference & Exposition and Milford Aquaculture Seminar*, Providence, RI

Krasnow, R., Gonzales, S., & Lindell, S. (2023). Improving Models of Kelp (*Saccharina latissima*) Aquaculture by Accounting for Regional Variation in Thermal Tolerance. Oral presentation. *Semester in Environmental Science Research Symposium*, Marine Biological Laboratory, Woods Hole, MA

Krasnow, R. (2023). Nonlinear Population Dynamics of Jonah Crab (*Cancer borealis*) in the Gulf of Maine. Poster. *Annual Biomedical Research Conference for Minoritized Scientists (ABRCMS)*, Phoenix, AZ

Krasnow, R. (2023). Nonlinear Dynamics of Jonah Crab in the Gulf of Maine: An Ecosystem Approach to Modeling an Emerging Fishery. Oral presentation. *BRITE REU Symposium*, Boston University, Boston, MA

Krasnow, R. (2023). ​​Modeling Macroalgae: Applications of Mathematics in Kelp Aquaculture. Poster. *Math for All - Boston Satellite Conference*, Boston College, Boston, MA

Krasnow, R., Cuddy, R., Kiffney, T., Marsh, J., & Brady, D. (2022). ​​Effects of environment and cultivation method on growth, appearance, and biofouling in oyster aquaculture. Poster. *Fall ClarkFEST,* Clark University, Worcester, MA

Krasnow, R., Cuddy, R., Kiffney, T., Marsh, J., & Brady, D. (2022). Effects of gear selection on oyster (*Crassostrea virginica*) mortality, growth, shape, and biofouling within a repurposed lobster pound. Poster. *SEA Fellows Symposium*, Downeast Institute, Beals, ME.
