---
title: "Resources"
---

These are documents and spreadsheets I have created for myself to keep track of useful links. Although they are personalized to my research interests and the tools I use most frequently, many of the resources could be useful for any kind of quantitative ecology.

Acknowledgement would always be welcome if you use these resources while preparing a manuscript, presentation, or other research product, but mostly I would just want to hear about the project! I am always looking to connect with people doing any sort of marine science, quantitative ecology, or applied data science, and I would love to talk about possible opportunities for collaboration.

### List of resources

This document is my [general "Resources" catch-all,](https://docs.google.com/document/d/1E9UgTfEbDLPmLYCFdKHk1VEAPRffNQN5_mK38vRWmo0/edit?usp=sharing) primarily focused on sites that I have found helpful when self-teaching concepts in R or general modeling/stats/data science.

<!-- This [Data Sources & Tools](https://docs.google.com/document/d/1ymJEjSLO0InMS4XKCxf5qN7RJjjPcwYyzzeayQGFzPI/edit?usp=sharing) document is more focused on sources of raw data for analysis, but the "To be classified" section at the bottom also includes links to more instructional sites, reference documents, etc. -->

### R packages

[This is a Google sheet containing a list of R packages](https://docs.google.com/spreadsheets/d/1VI1THL5XEfAE6w_QdG3LwXXNv0n4hxj5AuL9GkQdmBE/edit?usp=sharing) I want to keep track of for possible future use. It is roughly organized by topic, but many packages could fall under multiple categories.

The [CRAN Task Views](https://cran.r-project.org/web/views/) are an amazing place to find comprehensive guidance on which packages are suitable for a given task. Other sites to check out include [rOpenSci](https://ropensci.org/) and [Bioconductor](https://www.bioconductor.org/) (for bioinformatics packages).

### Journals

[This is a Google sheet containing a list of journals](https://docs.google.com/spreadsheets/d/1n9ZFF5Ly2pTv8vZCwCjUSlpPPoCGFotpNwNNpyMa0Us/edit?usp=sharing) that publish papers related to my areas of research. I have generally tried to exclude journals/publishers known to be predatory or egregiously exploit authors and/or reviewers, but have not rigorously checked them (e.g., using criteria suggested [here](https://guides.lib.odu.edu/publish/predatory) or [here](https://mdanderson.libanswers.com/faq/405538)).
